name: HarmonyHu's Blog
markdown: redcarpet
pygments: true
url: http://harmonyhu.com
paginate: 8
description: HarmonyHu's Blog
intro: Welcome to HarmonyHu's Blog
logo: https://github.com/HarmonyHu/harmonyhu.github.io/raw/master/_posts/images/logo.gif
disqus_shortname:
# url: http://gotchacode.com
#Comment out url when working locally to resolve base urls correctly
#url:

# Owner/author information
owner:
  name:           HarmonyHu
  avatar:         http://harmonyhu.com
  email:          harmonyhu@gmail.com
  # Social networking links used in footer. Update and remove as you like.
  twitter:
  github:
  stackexchange:
  # For Google Authorship https://plus.google.com/authorship
  google_plus:

# Analytics and webmaster tools stuff goes here
google_analytics:
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Links to include in top navigation
# For external links add external: true